# -*- coding: utf-8 -*-
"""student_score_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rnwh4YQA8vMWmI-B82f_1hxaRclR7TQI
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

data = pd.read_csv("students.csv")

X = data[['Hours']]
y = data['Scores']

model = LinearRegression()
model.fit(X,y)

prediction = model.predict(X)

mse = mean_squared_error(y, prediction)
mae = mean_absolute_error(y, prediction)
rmse = np.sqrt(mse)

print("MSE:", mse)
print("MAE:", mae)
print("RMSE:", rmse)

user_input = int(input("\nEnter number of hours to predict the score: "))
new_prediction = model.predict([[(user_input)]])[0]
print(f"The Score could be: ", new_prediction)

